service: hackcincy-athena-lambda

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "logs:*"
        - "s3:*"
        - "dynamodb:*"
        - "athena:*"
        - "xray:*"
        - "glue:*"
      Resource: "*"

functions:
  metrics:
    handler: index.handler
    timeout: 120
    events:
      - schedule: rate(5 minutes)
    environment:
      REGION: 'us-east-1'
      ATHENA_QUERY: 'SELECT * FROM "hackcincy2018"."user_metrics" LIMIT 1;'
      ATHENA_DB: hackcincy2018
      ATHENA_OUTPUT_LOCATION: 's3://hackcincy2018-athena-results'
