service: ga-alexa-demo # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "logs:*"
        - "s3:*"
        - "dynamodb:*"
        - "athena:*"
        - "xray:*"
        - "glue:*"
      Resource: "*"

functions:
  metrics:
    handler: index.handler
    events:
      - alexaSkill: amzn1.ask.skill.498c0431-be49-44bc-84e6-2076132f0b5d

